In [1]:
import pandas as pd

In [3]:
player_defense = pd.read_csv("../player_data/player_defense" + ".csv")
player_gca = pd.read_csv("../player_data/player_gca" + ".csv")
player_keepers = pd.read_csv("../player_data/player_keepers" + ".csv")
player_keepersadv = pd.read_csv("../player_data/player_keepersadv" + ".csv")
player_misc = pd.read_csv("../player_data/player_misc" + ".csv")
player_passing = pd.read_csv("../player_data/player_passing" + ".csv")
player_passing_types = pd.read_csv("../player_data/player_passing_types" + ".csv")
player_playingtime = pd.read_csv("../player_data/player_playingtime" + ".csv")
player_possession = pd.read_csv("../player_data/player_possession" + ".csv")
player_shooting = pd.read_csv("../player_data/player_shooting" + ".csv")
player_stats = pd.read_csv("../player_data/player_stats" + ".csv")

In [4]:
list_of_names = [player_defense, player_gca, player_keepers, player_keepersadv, 
                 player_misc, player_passing, player_passing_types, player_playingtime,
                player_possession, player_shooting, player_stats]

In [5]:
def remove_players_with_few_minutes(list_of_names):
    for i in list_of_names:
        i.drop(i[i['minutes_90s'] < 1.0].index, inplace=True)

In [6]:
remove_players_with_few_minutes(list_of_names)

In [8]:
def check_missing_values(player_dataset):
    print(player_dataset.isnull().sum())

In [135]:
check_missing_values(player_defense)

player                   0
position                 0
team                     0
age                      0
birth_year               0
minutes_90s              0
tackles                  0
tackles_won              0
tackles_def_3rd          0
tackles_mid_3rd          0
tackles_att_3rd          0
dribble_tackles          0
dribbles_vs              0
dribble_tackles_pct      0
dribbled_past            0
blocks                   0
blocked_shots            0
blocked_passes           0
interceptions            0
tackles_interceptions    0
clearances               0
errors                   0
dtype: int64

In [167]:
player_defense

,player,position,team,age,birth_year,minutes_90s,tackles,tackles_won,tackles_def_3rd,tackles_mid_3rd,...,dribbles_vs,dribble_tackles_pct,dribbled_past,blocks,blocked_shots,blocked_passes,interceptions,tackles_interceptions,clearances,errors
0,Aaron Mooy,MF,Australia,32-094,1990,4.0,9.0,6,4.0,4.0,...,8.0,75.0,2.0,6.0,4.0,2.0,3,12.0,9.0,0.0
1,Aaron Ramsey,MF,Wales,31-357,1990,3.0,2.0,0,0.0,2.0,...,2.0,0.0,2.0,4.0,1.0,3.0,0,2.0,2.0,1.0
2,Abdelhamid Sabiri,MF,Morocco,26-020,1996,2.0,3.0,1,1.0,2.0,...,6.0,33.3,4.0,3.0,1.0,2.0,5,8.0,3.0,0.0
3,Abdelkarim Hassan,DF,Qatar,29-112,1993,3.0,7.0,3,5.0,2.0,...,4.0,75.0,1.0,3.0,1.0,2.0,1,8.0,5.0,0.0
5,Abdessamad Ezzalzouli,FW,Morocco,21-001,2001,1.0,3.0,2,2.0,1.0,...,1.0,100.0,0.0,4.0,1.0,3.0,0,3.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
675,Ángel Di María,MF,Argentina,34-307,1988,3.2,3.0,1,2.0,0.0,...,3.0,33.3,2.0,3.0,0.0,3.0,1,4.0,0.0,0.0
676,Ángelo Preciado,DF,Ecuador,24-303,1998,2.9,7.0,5,3.0,3.0,...,4.0,50.0,2.0,2.0,0.0,2.0,6,13.0,4.0,0.0
677,Éder Militão,DF,Brazil,24-334,1998,3.9,7.0,6,4.0,1.0,...,4.0,75.0,1.0,1.0,0.0,1.0,3,10.0,5.0,0.0
678,Óscar Duarte,DF,Costa Rica,33-198,1989,3.0,4.0,2,4.0,0.0,...,2.0,100.0,0.0,3.0,1.0,2.0,6,10.0,15.0,0.0
679,İlkay Gündoğan,MF,Germany,32-055,1990,2.1,3.0,1,1.0,2.0,...,1.0,0.0,1.0,2.0,0.0,2.0,1,4.0,1.0,0.0

In [9]:
def show_missing_values(player_dataset, column):
    return player_dataset[player_dataset[column].isnull()]

In [132]:
show_missing_values(player_defense, 'tackles')

,player,position,team,age,birth_year,minutes_90s,tackles,tackles_won,tackles_def_3rd,tackles_mid_3rd,...,dribbles_vs,dribble_tackles_pct,dribbled_past,blocks,blocked_shots,blocked_passes,interceptions,tackles_interceptions,clearances,errors
268,Ismail Mohamad,FW,Qatar,32-257,1990,1.9,NaN,2,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN

In [10]:
def set_missing_values_to_zero(player_dataset, column):
    player_dataset[column] = player_dataset[column].fillna(0)

In [123]:
set_missing_values_to_zero(player_defense, 'dribble_tackles_pct')

In [11]:
def remove_other_missing_values(player_dataset):
    player_dataset.dropna(inplace=True)

In [134]:
remove_other_missing_values(player_defense)

## player_gca

In [136]:
check_missing_values(player_gca)

player             0
position           0
team               0
age                0
birth_year         0
minutes_90s        0
sca                1
sca_per90          1
sca_passes_live    1
sca_passes_dead    1
sca_dribbles       1
sca_shots          1
sca_fouled         1
sca_defense        1
gca                1
gca_per90          1
gca_passes_live    1
gca_passes_dead    1
gca_dribbles       1
gca_shots          1
gca_fouled         1
gca_defense        1
dtype: int64

In [138]:
show_missing_values(player_gca, 'gca_defense')

,player,position,team,age,birth_year,minutes_90s,sca,sca_per90,sca_passes_live,sca_passes_dead,...,sca_fouled,sca_defense,gca,gca_per90,gca_passes_live,gca_passes_dead,gca_dribbles,gca_shots,gca_fouled,gca_defense
268,Ismail Mohamad,FW,Qatar,32-257,1990,1.9,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [139]:
remove_other_missing_values(player_gca)

## player_keepers

In [141]:
check_missing_values(player_keepers)

player                         0
position                       0
team                           0
age                            0
club                           0
birth_year                     0
gk_games                       0
gk_games_starts                0
gk_minutes                     0
minutes_90s                    0
gk_goals_against               0
gk_goals_against_per90         0
gk_shots_on_target_against     0
gk_saves                       0
gk_save_pct                    0
gk_wins                        0
gk_ties                        0
gk_losses                      0
gk_clean_sheets                0
gk_clean_sheets_pct            0
gk_pens_att                    0
gk_pens_allowed                0
gk_pens_saved                  0
gk_pens_missed                 0
gk_pens_save_pct              22
dtype: int64

In [142]:
show_missing_values(player_keepers, 'gk_pens_save_pct')

,player,position,team,age,club,birth_year,gk_games,gk_games_starts,gk_minutes,minutes_90s,...,gk_wins,gk_ties,gk_losses,gk_clean_sheets,gk_clean_sheets_pct,gk_pens_att,gk_pens_allowed,gk_pens_saved,gk_pens_missed,gk_pens_save_pct
0,Aimen Dahmen,GK,Tunisia,25-324,CS Sfaxien,1997,3,3,270,3.0,...,1,1,1,2,66.7,0,0,0,0,NaN
1,Alireza Beiranvand,GK,IR Iran,30-088,Persepolis,1992,2,2,109,1.2,...,0,0,1,0,0.0,0,0,0,0,NaN
2,Alisson,GK,Brazil,30-077,Liverpool,1992,4,4,379,4.2,...,2,1,0,2,50.0,0,0,0,0,NaN
5,Danny Ward,GK,Wales,29-179,Leicester City,1993,2,1,94,1.0,...,0,0,1,0,0.0,0,0,0,0,NaN
6,Devis Epassy,GK,Cameroon,29-319,Abha,1993,2,2,180,2.0,...,1,1,0,1,50.0,0,0,0,0,NaN
7,Diogo Costa,GK,Portugal,23-090,Porto,1999,5,5,450,5.0,...,3,0,2,1,20.0,0,0,0,0,NaN
9,Ederson,GK,Brazil,29-123,Manchester City,1993,1,1,90,1.0,...,0,0,1,0,0.0,0,0,0,0,NaN
10,Edouard Mendy,GK,Senegal,30-292,Chelsea,1992,4,4,360,4.0,...,2,0,2,0,0.0,0,0,0,0,NaN
12,Gregor Kobel,GK,Switzerland,25-012,Dortmund,1997,1,1,90,1.0,...,1,0,0,0,0.0,0,0,0,0,NaN
15,Hossein Hosseini,GK,IR Iran,30-171,Esteghlal,1992,2,1,161,1.8,...,1,0,0,1,100.0,0,0,0,0,NaN
18,Kasper Schmeichel,GK,Denmark,36-043,Nice,1986,3,3,270,3.0,...,0,1,2,1,33.3,0,0,0,0,NaN
22,Manuel Neuer,GK,Germany,36-266,Bayern Munich,1986,3,3,270,3.0,...,1,1,1,0,0.0,0,0,0,0,NaN
23,Mathew Ryan,GK,Australia,30-254,FC Copenhagen,1992,4,4,360,4.0,...,2,0,2,2,50.0,0,0,0,0,NaN
25,Meshaal Barsham,GK,Qatar,24-307,Al Sadd SC,1998,2,2,180,2.0,...,0,0,2,0,0.0,0,0,0,0,NaN
26,Milan Borjan,GK,Canada,35-056,Red Star,1987,3,3,270,3.0,...,0,0,3,0,0.0,0,0,0,0,NaN
28,Munir,GK,Morocco,33-222,Al-Wehda,1989,1,1,90,1.0,...,1,0,0,1,100.0,0,0,0,0,NaN
32,Steve Mandanda,GK,France,37-265,Rennes,1985,1,1,90,1.0,...,0,0,1,0,0.0,0,0,0,0,NaN
34,Unai Simón,GK,Spain,25-190,Athletic Club,1997,4,4,390,4.3,...,1,2,1,2,50.0,0,0,0,0,NaN
35,Vanja Milinković-Savić,GK,Serbia,25-301,Torino,1997,3,3,270,3.0,...,0,1,2,0,0.0,0,0,0,0,NaN
36,Wayne Hennessey,GK,Wales,35-328,Nott'ham Forest,1987,2,2,175,1.9,...,0,1,0,0,0.0,0,0,0,0,NaN
39,Yann Sommer,GK,Switzerland,34-001,M'Gladbach,1988,3,3,270,3.0,...,1,0,2,1,33.3,0,0,0,0,NaN
40,Yassine Bounou,GK,Morocco,31-257,Sevilla,1991,6,6,570,6.3,...,2,2,2,3,50.0,0,0,0,0,NaN

In [143]:
set_missing_values_to_zero(player_keepers, 'gk_pens_save_pct')

In [144]:
check_missing_values(player_keepers)

player                        0
position                      0
team                          0
age                           0
club                          0
birth_year                    0
gk_games                      0
gk_games_starts               0
gk_minutes                    0
minutes_90s                   0
gk_goals_against              0
gk_goals_against_per90        0
gk_shots_on_target_against    0
gk_saves                      0
gk_save_pct                   0
gk_wins                       0
gk_ties                       0
gk_losses                     0
gk_clean_sheets               0
gk_clean_sheets_pct           0
gk_pens_att                   0
gk_pens_allowed               0
gk_pens_saved                 0
gk_pens_missed                0
gk_pens_save_pct              0
dtype: int64

## player_keepersadv

In [145]:
check_missing_values(player_keepersadv)

player                                   0
position                                 0
team                                     0
age                                      0
birth_year                               0
minutes_90s                              0
gk_goals_against                         0
gk_pens_allowed                          0
gk_free_kick_goals_against               0
gk_corner_kick_goals_against             0
gk_own_goals_against                     0
gk_psxg                                  0
gk_psnpxg_per_shot_on_target_against     0
gk_psxg_net                              0
gk_psxg_net_per90                        0
gk_passes_completed_launched             0
gk_passes_launched                       0
gk_passes_pct_launched                   0
gk_passes                                0
gk_passes_throws                         0
gk_pct_passes_launched                   0
gk_passes_length_avg                     0
gk_goal_kicks                            0
gk_pct_goal_kicks_launched               0
gk_goal_kick_length_avg                  0
gk_crosses                               0
gk_crosses_stopped                       0
gk_crosses_stopped_pct                   0
gk_def_actions_outside_pen_area          0
gk_def_actions_outside_pen_area_per90    0
gk_avg_distance_def_actions              0
dtype: int64

## player_misc

In [152]:
check_missing_values(player_misc)

player              0
position            0
team                0
age                 0
birth_year          0
minutes_90s         0
cards_yellow        0
cards_red           0
cards_yellow_red    0
fouls               0
fouled              0
offsides            0
crosses             0
interceptions       0
tackles_won         0
pens_won            0
pens_conceded       0
own_goals           0
ball_recoveries     0
aerials_won         0
aerials_lost        0
aerials_won_pct     0
dtype: int64

In [148]:
set_missing_values_to_zero(player_misc, 'aerials_won_pct')

In [150]:
show_missing_values(player_misc, 'pens_won')

,player,position,team,age,birth_year,minutes_90s,cards_yellow,cards_red,cards_yellow_red,fouls,...,crosses,interceptions,tackles_won,pens_won,pens_conceded,own_goals,ball_recoveries,aerials_won,aerials_lost,aerials_won_pct
268,Ismail Mohamad,FW,Qatar,32-257,1990,1.9,1,0,0,1,...,8,2,2,NaN,NaN,0,NaN,NaN,NaN,0.0

In [151]:
remove_other_missing_values(player_misc)

## player_passing

In [159]:
check_missing_values(player_passing)

player                         0
position                       0
team                           0
age                            0
birth_year                     0
minutes_90s                    0
passes_completed               0
passes                         0
passes_pct                     0
passes_total_distance          0
passes_progressive_distance    0
passes_completed_short         0
passes_short                   0
passes_pct_short               0
passes_completed_medium        0
passes_medium                  0
passes_pct_medium              0
passes_completed_long          0
passes_long                    0
passes_pct_long                0
assists                        0
xg_assist                      0
pass_xa                        0
xg_assist_net                  0
assisted_shots                 0
passes_into_final_third        0
passes_into_penalty_area       0
crosses_into_penalty_area      0
progressive_passes             0
dtype: int64

In [154]:
set_missing_values_to_zero(player_passing, 'passes_pct_long')

In [157]:
show_missing_values(player_passing, 'passes')

,player,position,team,age,birth_year,minutes_90s,passes_completed,passes,passes_pct,passes_total_distance,...,passes_pct_long,assists,xg_assist,pass_xa,xg_assist_net,assisted_shots,passes_into_final_third,passes_into_penalty_area,crosses_into_penalty_area,progressive_passes
268,Ismail Mohamad,FW,Qatar,32-257,1990,1.9,NaN,NaN,NaN,NaN,...,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [158]:
remove_other_missing_values(player_passing)

## player_passing_types

In [160]:
check_missing_values(player_passing_types)

player                   0
position                 0
team                     0
age                      0
birth_year               0
minutes_90s              0
passes                   1
passes_live              1
passes_dead              1
passes_free_kicks        1
through_balls            1
passes_switches          1
crosses                  0
throw_ins                1
corner_kicks             1
corner_kicks_in          1
corner_kicks_out         1
corner_kicks_straight    1
passes_completed         1
passes_offsides          1
passes_blocked           1
dtype: int64

In [161]:
show_missing_values(player_passing_types, 'passes')

,player,position,team,age,birth_year,minutes_90s,passes,passes_live,passes_dead,passes_free_kicks,...,passes_switches,crosses,throw_ins,corner_kicks,corner_kicks_in,corner_kicks_out,corner_kicks_straight,passes_completed,passes_offsides,passes_blocked
268,Ismail Mohamad,FW,Qatar,32-257,1990,1.9,NaN,NaN,NaN,NaN,...,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [162]:
remove_other_missing_values(player_passing_types)

## playing_time

In [184]:
check_missing_values(player_playingtime)

player                 0
position               0
team                   0
age                    0
birth_year             0
games                  0
minutes                0
minutes_per_game       0
minutes_pct            0
minutes_90s            0
games_starts           0
minutes_per_start      0
games_complete         0
games_subs             0
minutes_per_sub        0
unused_subs            0
points_per_game        0
on_goals_for           0
on_goals_against       0
plus_minus             0
plus_minus_per90       0
plus_minus_wowy        0
on_xg_for              0
on_xg_against          0
xg_plus_minus          0
xg_plus_minus_per90    0
xg_plus_minus_wowy     0
dtype: int64

In [180]:
show_missing_values(player_playingtime, 'xg_plus_minus_wowy')

,player,position,team,age,birth_year,games,minutes,minutes_per_game,minutes_pct,minutes_90s,...,on_goals_for,on_goals_against,plus_minus,plus_minus_per90,plus_minus_wowy,on_xg_for,on_xg_against,xg_plus_minus,xg_plus_minus_per90,xg_plus_minus_wowy
1,Aaron Mooy,MF,Australia,32-094,1990,4,360.0,90.0,100.0,4.0,...,4.0,6.0,-2.0,-0.50,NaN,2.3,7.2,-4.9,-1.23,NaN
5,Abdelkarim Hassan,DF,Qatar,29-112,1993,3,270.0,90.0,100.0,3.0,...,1.0,7.0,-6.0,-2.00,NaN,1.4,3.5,-2.1,-0.71,NaN
25,Aimen Dahmen,GK,Tunisia,25-324,1997,3,270.0,90.0,100.0,3.0,...,1.0,1.0,0.0,0.00,NaN,2.3,2.8,-0.5,-0.17,NaN
27,Akram Afif,FW,Qatar,26-030,1996,3,270.0,90.0,100.0,3.0,...,1.0,7.0,-6.0,-2.00,NaN,1.4,3.5,-2.1,-0.71,NaN
51,Alistair Johnston,DF,Canada,24-071,1998,3,270.0,90.0,100.0,3.0,...,2.0,7.0,-5.0,-1.67,NaN,4.2,3.9,0.3,0.11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,Vanja Milinković-Savić,GK,Serbia,25-301,1997,3,270.0,90.0,100.0,3.0,...,5.0,8.0,-3.0,-1.00,NaN,3.4,7.3,-3.9,-1.32,NaN
788,Wojciech Szczęsny,GK,Poland,32-244,1990,4,360.0,90.0,100.0,4.0,...,3.0,5.0,-2.0,-0.50,NaN,4.5,7.3,-2.7,-0.69,NaN
801,Yassine Meriah,DF,Tunisia,29-169,1993,3,270.0,90.0,100.0,3.0,...,1.0,1.0,0.0,0.00,NaN,2.3,2.8,-0.5,-0.17,NaN
810,Youssouf Sabaly,DF,Senegal,29-288,1993,4,360.0,90.0,100.0,4.0,...,5.0,7.0,-2.0,-0.50,NaN,4.6,3.5,1.0,0.26,NaN
826,Óscar Duarte,DF,Costa Rica,33-198,1989,3,270.0,90.0,100.0,3.0,...,3.0,11.0,-8.0,-2.67,NaN,1.4,10.1,-8.7,-2.90,NaN

In [172]:
player_playingtime.drop(player_playingtime[player_playingtime['games'] == 0].index, inplace=True)

In [181]:
set_missing_values_to_zero(player_playingtime, 'minutes_per_start')
set_missing_values_to_zero(player_playingtime, 'minutes_per_sub')
set_missing_values_to_zero(player_playingtime, 'plus_minus_wowy')
set_missing_values_to_zero(player_playingtime, 'xg_plus_minus_wowy')

In [183]:
remove_other_missing_values(player_playingtime)

## player_possession

In [188]:
check_missing_values(player_possession)

player                         0
position                       0
team                           0
age                            0
birth_year                     0
minutes_90s                    0
touches                        0
touches_def_pen_area           0
touches_def_3rd                0
touches_mid_3rd                0
touches_att_3rd                0
touches_att_pen_area           0
touches_live_ball              0
dribbles_completed             0
dribbles                       0
dribbles_completed_pct         0
miscontrols                    0
dispossessed                   0
passes_received                0
progressive_passes_received    0
dtype: int64

In [186]:
set_missing_values_to_zero(player_possession, 'dribbles_completed_pct')

In [187]:
remove_other_missing_values(player_possession)

## player_shooting

In [194]:
check_missing_values(player_shooting)

player                      0
position                    0
team                        0
age                         0
birth_year                  0
minutes_90s                 0
goals                       0
shots                       0
shots_on_target             0
shots_on_target_pct         0
shots_per90                 0
shots_on_target_per90       0
goals_per_shot              0
goals_per_shot_on_target    0
average_shot_distance       0
shots_free_kicks            1
pens_made                   0
pens_att                    0
xg                          1
npxg                        1
npxg_per_shot               0
xg_net                      1
npxg_net                    1
dtype: int64

In [193]:
set_missing_values_to_zero(player_shooting, 'shots_on_target_pct')
set_missing_values_to_zero(player_shooting, 'goals_per_shot')
set_missing_values_to_zero(player_shooting, 'goals_per_shot_on_target')
set_missing_values_to_zero(player_shooting, 'average_shot_distance')
set_missing_values_to_zero(player_shooting, 'npxg_per_shot')

In [195]:
remove_other_missing_values(player_shooting)

## player_stats

In [14]:
check_missing_values(player_stats)

player                      0
position                    0
team                        0
age                         0
club                        0
birth_year                  0
games                       0
games_starts                0
minutes                     0
minutes_90s                 0
goals                       0
assists                     0
goals_pens                  0
pens_made                   0
pens_att                    0
cards_yellow                0
cards_red                   0
goals_per90                 0
assists_per90               0
goals_assists_per90         0
goals_pens_per90            0
goals_assists_pens_per90    0
xg                          0
npxg                        0
xg_assist                   0
npxg_xg_assist              0
xg_per90                    0
xg_assist_per90             0
xg_xg_assist_per90          0
npxg_per90                  0
npxg_xg_assist_per90        0
dtype: int64

In [13]:
remove_other_missing_values(player_stats)

In [201]:
player_defense.to_csv(r'data/player_defense.csv', index=False)
player_gca.to_csv(r'data/player_gca.csv', index=False)
player_keepers.to_csv(r'data/player_keepers.csv', index=False)
player_keepersadv.to_csv(r'data/player_keepersadv.csv', index=False)
player_misc.to_csv(r'data/player_misc.csv', index=False)
player_passing.to_csv(r'data/player_passing.csv', index=False)
player_passing_types.to_csv(r'data/player_passing_types.csv', index=False)
player_playingtime.to_csv(r'data/player_playingtime.csv', index=False)
player_possession.to_csv(r'data/player_possession.csv', index=False)
player_defense.to_csv(r'data/player_defense.csv', index=False)
player_shooting.to_csv(r'data/player_shooting.csv', index=False)

In [15]:
player_stats.to_csv(r'../data/player_stats.csv', index=False)